#baseURL = "http://example.org/"
#languageCode = "en-us"
#title = "My New Hugo Site"
#theme = "alageek"

author = "Gökmen Görgen"
baseurl = "/"
canonifyurls = true
copyright = "Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved."
paginate = 3
theme = "alageek"
title = "Arsalan Pirzada"

[params]
copyright = "© 2018 by Arsalan Pirzada"
copyrightUrl = "https://www.arsalanpirzada.com/"
faviconfile = "https://www.arsalanpirzada.com/favicon.ico"
latestpostcount = 5
logofile = "http://placehold.jp/120x120.png"
highlightjs = true

[[params.featured_posts]]
title = "Migrate to Hugo from Jekyll"
url = "/blog/migrate-from-jekyll/"

[[menu.primary]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 10

[[menu.primary]]
identifier = "about"
name = "About"
url = "/about/"
weight = 20

[[menu.primary]]
identifier = "work"
name = "Work"
url = "/work/"
weight = 30

[[menu.secondary]]
identifier = "email"
name = "Contact"
url = "mailto:public@arsalanpirzada.com"
weight = 110

[[menu.secondary]]
identifier = "github"
name = "GitHub"
url = "https://github.com/arsalan86"
weight = 120

[[menu.secondary]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/arsalan-pirzada-495375146/"
weight = 130

[[menu.secondary]]
identifier = "feed"
name = "Feed"
url = "http://localhost:1313/index.xml"
weight = 130
